### ISSUE TITLE
The non-use of Gurmukhi digits?

### ISSUE THREAD

**Issue by DavidHaslam** [FreeBiblesIndia/Punjabi_Bible#7]
A search for the regexp `[\x{0A66}-\x{0A6F}]` gave no hits, showing that no use is made of **Gurmukhi digits**.

i.e. All scripture references in **parallel passage** markers and **book introductions** use ordinary Western digits for chapter and verse **numbers** and the numerical part of some book names.

Even so, this prompts the question:
> **Why not use the Gurmukhi digits in the Punjabi Bible ?**

**Comment by joshykurian** [comment]
The present generation (especially the youth) uses the western digits and no longer use Gurmukhi digits.

**Comment by DavidHaslam** [comment]
_Thanks._
